### ISSUE TITLE
Can't build libstrophe because there is no PLIST file

### ISSUE THREAD

**Issue by Jajauma** [NetBSD/pkgsrc#108]
Hello,

on the trunk branch, the port of the chat/libstrophe library does not contain a PLIST file and the build stops with an error

```
$ bmake
=> Bootstrap dependency digest>=20211023: found digest-20220214
ERROR: This package has set PKG_FAIL_REASON:
ERROR: Missing PLIST file or PLIST/GENERATE_PLIST definition.
*** Error code 1

Stop.
```
Do you need to prepare this file yourself or is it missing due to some error?

**Comment by Jajauma** [comment]
Perhaps such a simple auto-generated file will do:

```
@comment $NetBSD $
include/strophe.h
lib/libstrophe.a
lib/libstrophe.la
lib/libstrophe.so
lib/libstrophe.so.0
lib/libstrophe.so.${PKGVERSION}
lib/pkgconfig/libstrophe.pc
```

**Comment by dhgutteridge** [comment]
Hello,

This file just got accidentally missed from the commit, I assume. I've fixed it now (in our CVS tree -- should replicate here in a couple of hours). Thanks for reporting this.

**Comment by Jajauma** [comment]
It worked, thank you.
