### ISSUE TITLE
Error when bootstraping libarchive

### ISSUE THREAD

**Issue by z-zeechung** [NetBSD/pkgsrc#140]
I'm not sure if this is the proper place to ask question about pkgsrc... I'm trying to bootstrap pkgsrc on win95, and I've successfully compiled the first few packages. However, I encountered an unsolvable problem when compiling libarchive.
![屏幕截图 2024-05-29 190422](https://github.com/NetBSD/pkgsrc/assets/152474942/1819570d-0039-4a48-8406-f7d672bbd632)
I can find both archive_acl.Tpo and archive_acl.Plo under .deps folder. I've confirmed that the mv command I'm using is functioning correctly that can overwrite existing file. Also, it seems that win95 doesn't have a permission management machansim. So I just cannot figure out what is going wrong and I'm seeking for help.

**Comment by bsiegert** [comment]
This is *not* a good place to ask such a question. It would be better to ask this on a mailing list, such as the pkgsrc-users list.

**Comment by z-zeechung** [comment]
All right, I'll do that.
