### ISSUE TITLE
Allow for set default environment variables on user side

### ISSUE THREAD

**Issue by bartoszkosiorek** [NetBSD/pkgsrc#76]
It will be great to allow set the default environment variables on User side.

For example after installing client bootstrap and packages, it would be nice to be able to set defaul environment variables, with command:

`source /usr/local/pkg/env.sh`

The file will contain default variables, for example:
```
export PKGSRC_HOME=/usr/local/pkg

export CMAKE_C_COMPILER=${PKGSRC_HOME}/bin/clang
export CMAKE_CXX_COMPILER=${PKGSRC_HOME}/bin/clang++
export PYTHON=${PKGSRC_HOME}/bin/python2.7
export PYTHON3=${PKGSRC_HOME}/bin/python3.7
export JAVA_HOME=${PKGSRC_HOME}/java/adoptopenjdk11-bin
```

It would simplify the setup process.
Do you know how to implement that?

**Comment by krytarowski** [comment]
Set PATH, JAVA_HOME etc in your .profile and be done?

**Comment by bartoszkosiorek** [comment]
I would like to use it in CI. So it would be much easier to have only one file to include.
With that solution everything would be set automatically and it will be connected with PkgSrc release.

Also for developers it will be much easier to setup. They need to just inclue one file. After upgrade PkgSrc, the file (with eg. `PATH`, `JAVA_HOME`) could be also updated.

**Comment by krytarowski** [comment]
Unless I miss something, you need to write this file yourself.

**Comment by bartoszkosiorek** [comment]
Thanks. I will do that.
