### ISSUE TITLE
autoconf to 2.70 breaks building gmake on apple silicon.

### ISSUE THREAD

**Issue by CamilleScholtz** [NetBSD/pkgsrc#81]
With the error `fork resource temporarily unavailable` when executing `missing`, one of the files updated: https://github.com/NetBSD/pkgsrc/commit/6f08110dec4d86750aa0115a80b2cff44725fda6

Reverting to before this update fixes the error. I don't know if this only happens on macos, apple silicon, or what though.

**Comment by iamleot** [comment]
@Midar can you please give it a look? (over to committer)

**Comment by Midar** [comment]
Reproduced. This is indeed caused by the updated `missing`. I reverted `missing` and removed the comment in `devel/autoconf/Makefile` that says to update it, so that the next person updating autoconf does not break it again. Please verify this fixes it for you.

**Comment by Midar** [comment]
Closing as there has been no response, so I assume the fix for x86_64 also works on ARM. Please reopen if the issue persists.
