### ISSUE TITLE
outdated software description: nanogrep

### ISSUE THREAD

**Issue by loannaflip** [NetBSD/pkgsrc#82]
update nanogrep's description. It has been changed recently.

**Comment by bsiegert** [comment]
Would you like to propose a patch?

**Comment by loannaflip** [comment]
~~Opened a PR #83~~ closed (unnecessary)

**Comment by loannaflip** [comment]
https://github.com/Uniminin/nanogrep/releases/tag/1.2.1 has been merged but the description was not updated when it was changed in 1.2.1 update.

**Comment by loannaflip** [comment]
new released just launched. Hopefully this issue will be fixed~
