### ISSUE TITLE
anyplans on regaining support for freebsd and fixing bootstrap for it

### ISSUE THREAD

**Issue by justfly1111** [NetBSD/pkgsrc#94]
anyplans on regaining support for freebsd and fixing bootstrap for it

**Comment by bsiegert** [comment]
Can you be any more specific? I just ran a bootstrap on FreeBSD 12, and it 
completed just fine. FreeBSD is supposed to be a supported target OS.

**Comment by alarixnia** [comment]
I was able to bootstrap on FreeBSD 13 with clang yesterday. I think this can be closed.

**Comment by justfly1111** [comment]
awesome im going to try and bootstrap it now on current there was a notification in the bootstrap readme id say for about a year saying it was broken on freebsd thanks for letting me know much appreciated

**Comment by justfly1111** [comment]
bootstrap is a negative on  working on 14.0-current  due to circular dependency of gcc6 and cwrappers  openning new issue for that with the output 

gcc -DHAVE\_CONFIG\_H -I/usr/pkgsrc/bootstrap/work/libnbcompat -I/usr/pkgsrc/bootstrap/work/libarchive/libarchive -I. -I. -I../lib -DBOOTSTRAP -g -O2 -c show.c  
gcc -L/usr/pkgsrc/bootstrap/work/libnbcompat -L../lib -o pkg\_info main.o perform.o show.o -linstall  -lnbcompat  
\===> running: /bin/sh /usr/pkgsrc/bootstrap/work/bin/install-sh -c -o root -g wheel -m 755 /usr/pkgsrc/bootstrap/work/pkg\_install/add/pkg\_add /usr/pkgsrc/bootstrap/work/sbin/pkg\_add  
\===> running: /bin/sh /usr/pkgsrc/bootstrap/work/bin/install-sh -c -o root -g wheel -m 755 /usr/pkgsrc/bootstrap/work/pkg\_install/admin/pkg\_admin /usr/pkgsrc/bootstrap/work/sbin/pkg\_admin  
\===> running: /bin/sh /usr/pkgsrc/bootstrap/work/bin/install-sh -c -o root -g wheel -m 755 /usr/pkgsrc/bootstrap/work/pkg\_install/create/pkg\_create /usr/pkgsrc/bootstrap/work/sbin/pkg\_create  
\===> running: /bin/sh /usr/pkgsrc/bootstrap/work/bin/install-sh -c -o root -g wheel -m 755 /usr/pkgsrc/bootstrap/work/pkg\_install/info/pkg\_info /usr/pkgsrc/bootstrap/work/sbin/pkg\_info  
\===> running: (cd /usr/pkgsrc/pkgtools/cwrappers && /usr/pkgsrc/bootstrap/work/bin/bmake  MAKE\_JOBS=1 PKG\_COMPRESSION=none PKGSRC\_KEEP\_BIN\_PKGS=no MAKECONF=/usr/pkgsrc/bootstrap/work/mk.conf install)  
\===> Installing dependencies for cwrappers-20180325  
\=> Build dependency gcc6>=6.1: NOT found  
\=> Verifying reinstall for ../../lang/gcc6  
\=> Bootstrap dependency digest>=20211023: NOT found  
\=> Verifying reinstall for ../../pkgtools/digest  
\===> Installing dependencies for digest-20211023  
\=> Build dependency cwrappers>=20150314: NOT found  
\=> Verifying reinstall for ../../pkgtools/cwrappers  
ERROR: This package has set PKG\_FAIL\_REASON:  
ERROR: Circular dependency detected  
\*\*\* Error code 1

Stop.  
bmake\[3\]: stopped in /usr/pkgsrc/pkgtools/cwrappers  
\*\*\* Error code 1

Stop.  
bmake\[2\]: stopped in /usr/pkgsrc/pkgtools/digest  
\*\*\* Error code 1

Stop.  
bmake\[1\]: stopped in /usr/pkgsrc/lang/gcc6  
\*\*\* Error code 1

Stop.  
bmake: stopped in /usr/pkgsrc/pkgtools/cwrappers  
\===> exited with status 1  
aborted.

**Comment by justfly1111** [comment]
i tried it it bootstraps with clang but gcc fails due to circular dependancy if anyone wants to fix that but it does compile with clang just not gcc

**Comment by justfly1111** [comment]
works clang fails with gcc

**Comment by alarixnia** [comment]
If you want to bootstrap with gcc you need to provide some copy of GCC outside pkgsrc and point pkgsrc to it.
